<?php
/*
 * Implementing hook_permission
 */
function copycat_permission(){
   return array(
    'use copycat' => array(
      'title' => t('Edit content inline'), 
      'description' => t('Use copycat for inline editting.'),
    ),
  );
}

/** Implementing hook_menu
 *
 * @return array 
 */
function copycat_menu(){
  $items = array();
    $items['ajax/copycat'] = array(
    'page callback' => 'copycat_edit',
    'access arguments' => array('use copycat'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function copycat_edit(){
  
}